import {
	SiJavascript,
	SiTypescript,
	SiCss3,
	SiHtml5,
	SiReact,
	SiAngular,
	SiVuedotjs,
	SiSvelte,
	SiSass,
	SiLess,
	SiPython,
	SiRuby,
	SiPhp,
	SiGo,
	SiRust,
	SiOpenjdk,
	SiC,
	SiCplusplus,
	SiCsharp,
	SiDotnet,
	SiMysql,
	SiPostgresql,
	SiSqlite,
	SiYaml,
	SiJson,
	SiMarkdown,
	SiGnubash,
	SiPowershell,
	SiDocker,
	SiKubernetes,
	SiGraphql,
	SiSwift,
	SiKotlin,
	SiDart,
	SiFlutter,
	SiNodedotjs,
	SiPerl,
	SiScala,
	SiHaskell,
	SiLua,
	SiR,
	SiToml,
	SiNginx,
} from "react-icons/si";

export const icons = {
	js: SiJavascript,
	jsx: SiReact,
	ts: SiTypescript,
	tsx: SiReact,
	css: SiCss3,
	html: SiHtml5,
	react: SiReact,
	angular: SiAngular,
	vue: SiVuedotjs,
	svelte: SiSvelte,
	sass: SiSass,
	scss: SiSass,
	less: SiLess,
	python: SiPython,
	py: SiPython,
	ruby: SiRuby,
	rb: SiRuby,
	php: SiPhp,
	go: SiGo,
	golang: SiGo,
	rust: SiRust,
	rs: SiRust,
	java: SiOpenjdk,
	c: SiC,
	cpp: SiCplusplus,
	"c++": SiCplusplus,
	csharp: SiCsharp,
	cs: SiCsharp,
	dotnet: SiDotnet,
	sql: SiMysql,
	mysql: SiMysql,
	postgresql: SiPostgresql,
	postgres: SiPostgresql,
	sqlite: SiSqlite,
	yaml: SiYaml,
	yml: SiYaml,
	json: SiJson,
	markdown: SiMarkdown,
	md: SiMarkdown,
	bash: SiGnubash,
	sh: SiGnubash,
	shell: SiGnubash,
	powershell: SiPowershell,
	ps1: SiPowershell,
	docker: SiDocker,
	dockerfile: SiDocker,
	kubernetes: SiKubernetes,
	k8s: SiKubernetes,
	graphql: SiGraphql,
	gql: SiGraphql,
	swift: SiSwift,
	kotlin: SiKotlin,
	kt: SiKotlin,
	dart: SiDart,
	flutter: SiFlutter,
	node: SiNodedotjs,
	perl: SiPerl,
	scala: SiScala,
	haskell: SiHaskell,
	hs: SiHaskell,
	lua: SiLua,
	r: SiR,
	toml: SiToml,
	nginx: SiNginx,
	// Add more icons as needed
};
